### ISSUE TITLE
License!

### ISSUE THREAD

**Issue by davidebangelista** [Pizza20/Ry-operating-system-For-C-drive#1]
This code is taken from my VOX project.

Please update your code to GPLv3, you have ~30 days. (Not a threat, I swear!)

Thanks!

**Comment by Pizza20** [comment]
Oh, sorry I forgot

**Comment by Pizza20** [comment]
can you review it to make sure I did it right?

**Comment by davidebangelista** [comment]
Yup. Looks good! (Closing issue)
